security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new,      role: IS_AUTHENTICATED_FULLY }
        - { path: ^/create,   role: IS_AUTHENTICATED_FULLY }
        - { path: ^/genres/,  role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Kinosklad\Bundle\MainBundle\Entity\User
